version: '3'
services:
  # Traefik proxy to handle all container traffic
  traefik:
    image: traefik:latest
    container_name: traefik
    network_mode: host
    restart: always
    command:
      # Add docker as a provider
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      # Enable API dashboard
      - --api.dashboard=true
      # Certificate Resolver
      - --certificatesresolvers.letsencrypt.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      # HTTP entrypoint just re-directs to https
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      # HTTPS entrypoint
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      - --entrypoints.https.http.tls.domains[0].main=$CLOUDFLARE_DOMAIN
      - --entrypoints.https.http.tls.domains[0].sans=*.$CLOUDFLARE_DOMAIN
      # Metrics
      - --metrics.prometheus=true
      - --metrics.prometheus.manualrouting=true
    environment:
      CLOUDFLARE_EMAIL: $CLOUDFLARE_EMAIL
      CLOUDFLARE_DNS_API_TOKEN: $CLOUDFLARE_DNS_API_TOKEN
    volumes:
      - ${CORE_HOME}/traefik/etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      # Cockpit management portal (works here as Traefik is network_mode: host)
      traefik.http.services.cockpit.loadbalancer.server.port: 9090
      traefik.http.routers.cockpit.rule: Host(`${COCKPIT_HOST}`)
      traefik.http.routers.cockpit.entrypoints: https
      traefik.http.routers.cockpit.service: cockpit
      traefik.http.routers.cockpit.middlewares: local-whitelist@docker
      # Traefik dashboard router
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.rule: Host(`${TRAEFIK_HOST}`)
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: local-whitelist@docker
      # Traefik prometheus metrics
      traefik.http.services.traefik-metrics.loadbalancer.server.port: 8080
      traefik.http.routers.traefik-metrics.rule: Host(`${TRAEFIK_HOST}`) && PathPrefix(`/metrics`)
      traefik.http.routers.traefik-metrics.entrypoints: https
      traefik.http.routers.traefik-metrics.service: prometheus@internal
      traefik.http.routers.traefik-metrics.middlewares: local-whitelist@docker
      # Local whitelist middleware
      traefik.http.middlewares.local-whitelist.ipwhitelist.sourcerange: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16


  # Pi-Hole for local DNS resolution
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      VIRTUAL_HOST: $PIHOLE_HOST
      WEBPASSWORD: $PIHOLE_TOKEN
    ports:
      - 192.168.0.100:53:53/tcp
      - 192.168.0.100:53:53/udp
    volumes:
      - ${CORE_HOME}/pihole/pihole:/etc/pihole
      - ${CORE_HOME}/pihole/dnsmasq.d:/etc/dnsmasq.d
    depends_on:
      - traefik
    restart: always
    labels:
      traefik.enable: true
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.routers.pihole.rule: Host(`$PIHOLE_HOST`)
      traefik.http.routers.pihole.entrypoints: https
      traefik.http.routers.pihole.middlewares: local-whitelist@docker

  pihole-exporter:
    image: ekofr/pihole-exporter
    restart: unless-stopped
    environment:
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PASSWORD: $PIHOLE_TOKEN
    depends_on:
      - pihole
    labels:
      traefik.enable: true
      traefik.http.services.pihole-exporter.loadbalancer.server.port: 9617
      traefik.http.routers.pihole-exporter.rule: Host(`$PIHOLE_HOST`) && PathPrefix(`/metrics`)
      traefik.http.routers.pihole-exporter.entrypoints: https
      traefik.http.routers.pihole-exporter.middlewares: local-whitelist@docker


  # Portainer for docker container management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CORE_HOME}/portainer/data:/data
    depends_on:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.rule: Host(`$PORTAINER_HOST`)
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.middlewares: local-whitelist@docker
