- name: Install Nginx Proxy Manager
  become: true
  community.docker.docker_container:
    name: nginx-proxy-manager
    pull: always
    restart_policy: always
    image: jc21/nginx-proxy-manager:latest
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /data/npm/data:/data
      - /data/letsencrypt:/etc/letsencrypt
