version: '3'
services:
  minecraft-server:
    image: itzg/minecraft-server:java17-alpine
    restart: unless-stopped
    user: $UID:$PID
    ports:
      - 25565:25565
      - 8080:8080
    environment:
      EULA: true
      TYPE: paper
      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
      ENABLE_ROLLING_LOGS: true
      VERSION: 1.20.1
    volumes:
      - $MINECRAFT_HOME/data:/data
    labels:
      traefik.enable: true
      traefik.http.services.minecraft-bluemap.loadbalancer.server.port: 8123
      traefik.http.routers.minecraft-bluemap.rule: Host(`minecraft-map.ggrainger.uk`)
      traefik.http.routers.minecraft-bluemap.entrypoints: https