version: "3"
services:
  server:
    image: ghcr.io/whykickamoocow/dsp-docker-server:master
    ports: 
      - 8469:8469
    command:
      - ${STEAM_USERNAME}
      - ${STEAM_PASSWORD}
      - ${STEAM_MFA}
    volumes:
      - ${DSP_HOME}/game:/game
      - ${DSP_HOME}/save:/save