version: '3'
services:
  barotrauma:
    image: randomman552/barotrauma:latest
    container_name: barotrauma
    restart: unless-stopped
    environment:
      - PGID=$BAROTRAUMA_UID
      - PUID=$BAROTRAUMA_PID
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    volumes:
      - ${BAROTRAUMA_HOME}/data:/home/baro/.local/share/Daedalic Entertainment GmbH/Barotrauma
      - ${BAROTRAUMA_HOME}/config:/server/Data