version: '3.8'
services:
  forever-stranded:
    image: itzg/minecraft-server:java8-multiarch
    container_name: forever-stranded
    user: 1600:1600
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - TYPE=CURSEFORGE
      - CF_SERVER_MOD=Forever+Stranded-1.9.9.1+Server+Files.zip
      - CF_BASE_DIR=/data
      - EULA=true
      - INIT_MEMORY=1G
      - MAX_MEMORY=8G
      - ENABLE_ROLLING_LOGS=true
    volumes:
      - /storage/games/minecraft/forever-stranded:/data