version: '3'
services:
  server:
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - ${UPTIME_KUMA_HOME}/data:/app/data:rw
    labels:
      traefik.enable: true
      traefik.http.services.deluge.loadbalancer.server.port: 3001
      traefik.http.routers.deluge.rule: Host(`${UPTIME_KUMA_HOST}`)
      traefik.http.routers.deluge.entrypoints: https