# Service to send automatic emails relating to smart status of drives
version: '3.8'
services:
  # Device monitor
  smartmontools:
    image: gists/smartmontools
    container_name: smartmontools-smartd
    restart: unless-stopped
    privileged: true
    hostname: $SERVER_HOSTNAME
    depends_on:
      - mail
    volumes:
      - ${SMARTMONTOOLS_HOME}/smartd.conf:/etc/smartd.conf
      - ${SMARTMONTOOLS_HOME}/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ${SMARTMONTOOLS_HOME}/revaliases:/etc/ssmtp/revaliases
  
  # Mail server (postfix relay)
  mail:
    image: juanluisbaptiste/postfix:latest
    container_name: smartmontools-mail
    restart: unless-stopped
    hostname: $SERVER_HOSTNAME
    environment:
      SMTP_SERVER: $SMTP_SERVER
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      OVERWRITE_FROM: $SMTP_EMAIL
      SERVER_HOSTNAME: $SERVER_HOSTNAME
    volumes:
      - /etc/localtime:/etc/localtime:ro