# Install htop
- name: Install utilities
  ansible.builtin.apt:
    name:
      - htop
      - btop
      - rsync

# Copy configuration
- name: Copy rsync Config
  ansible.builtin.copy:
    mode: "0544"
    src: rsyncd.conf
    dest: /etc/rsyncd.conf

# Ensure rsyncd is stopped by default
- name: Stop and Disable rsync
  ansible.builtin.service:
    enabled: false
    name: rsync
    state: stopped

# Configure sshd
- name: Copy sshd Config
  ansible.builtin.copy:
    mode: "0544"
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart SSHD
