# Install htop
- name: install utilities
  ansible.builtin.apt:
    name:
      - htop
      - btop
      - rsync

# Gen locale
- name: configure locale-gen
  ansible.builtin.copy:
    mode: "0644"
    src: locale.gen
    dest: /etc/locale.gen
  notify:
    - gen locale

# Configre locale
- name: configure default locale
  ansible.builtin.copy:
    mode: "0644"
    src: locale
    dest: /etc/default/locale

# Copy configuration
- name: configure rsync
  ansible.builtin.copy:
    mode: "0644"
    src: rsyncd.conf
    dest: /etc/rsyncd.conf

# Ensure rsyncd is stopped by default
- name: stop and disable rsync
  ansible.builtin.service:
    enabled: false
    name: rsync
    state: stopped

# Configure sshd
- name: configure sshd
  ansible.builtin.copy:
    mode: "0644"
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd
