# Install htop
- name: Install utilities
  become: true
  ansible.builtin.apt:
    name:
      - htop
      - btop
      - rsync

# Gen locale
- name: Configure locale-gen
  become: true
  ansible.builtin.copy:
    mode: "0644"
    src: locale.gen
    dest: /etc/locale.gen
  notify:
    - Generate locale

# Configre locale
- name: Configure default locale
  become: true
  ansible.builtin.copy:
    mode: "0644"
    src: locale
    dest: /etc/default/locale

# Copy configuration
- name: Configure rsync
  become: true
  ansible.builtin.copy:
    mode: "0644"
    src: rsyncd.conf
    dest: /etc/rsyncd.conf

# Ensure rsyncd is stopped by default
- name: Stop + disable rsync
  become: true
  ansible.builtin.service:
    enabled: false
    name: rsync
    state: stopped

# Configure sshd
- name: Configure sshd
  become: true
  ansible.builtin.copy:
    mode: "0644"
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart sshd
