- name: Restart sshd
  become: true
  ansible.builtin.service:
    state: restarted
    name: sshd

- name: Generate locale
  become: true
  changed_when: false
  ansible.builtin.command:
    cmd: locale-gen
