version: '3.8'
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homepage-dockerproxy
    environment:
        - CONTAINERS=1
        - POST=0
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ${HOMEPAGE_HOME}/config:/app/config
      - ${HOMEPAGE_HOME}/icons:/app/public/icons
    labels:
      traefik.enable: true
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.http.routers.homepage.rule: Host(`$HOMEPAGE_URL`)
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.middlewares: local-whitelist
      traefik.http.middlewares.local-whitelist.ipwhitelist.sourcerange: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
