version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: ${JELLYFIN_UID:-1000}:${JELLYFIN_GID:-1000}
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ${JELLYFIN_HOME}/config:/config
      - ${JELLYFIN_HOME}/cache:/cache
      - ${MEDIA_HOME}/data:/media
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    labels:
      traefik.enable: true
      # Middleware
      traefik.http.middlewares.jellyfin-security.headers.customresponseheaders.X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.http.middlewares.jellyfin-security.headers.SSLRedirect: true
      traefik.http.middlewares.jellyfin-security.headers.STSSeconds: 315360000
      traefik.http.middlewares.jellyfin-security.headers.STSIncludeSubdomains: true
      traefik.http.middlewares.jellyfin-security.headers.STSPreload: true
      traefik.http.middlewares.jellyfin-security.headers.frameDeny: true
      traefik.http.middlewares.jellyfin-security.headers.contentTypeNosniff: true
      traefik.http.middlewares.jellyfin-security.headers.browserXSSFilter: true
      traefik.http.middlewares.jellyfin-security.headers.customFrameOptionsValue: allow-from https://$JELLYFIN_HOST
      # HTTP Service
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.routers.jellyfin.rule: Host(`${JELLYFIN_HOST}`) && !PathPrefix(`/metrics`)
      traefik.http.routers.jellyfin.entrypoints: https
      traefik.http.routers.jellyfin.middlewares: jellyfin-security

  jellyfin-exporter:
    image: randomman552/jellyfin-prometheus-exporter
    restart: unless-stopped
    environment:
      JELLYFIN_URL: https://$JELLYFIN_HOST
      JELLYFIN_API_KEY: $JELLYFIN_PROM_API_KEY
    depends_on:
      - jellyfin
    labels:
      traefik.enable: true
      traefik.http.services.jellyfin-metrics.loadbalancer.server.port: 2112
      traefik.http.routers.jellyfin-metrics.service: jellyfin-metrics
      traefik.http.routers.jellyfin-metrics.rule: Host(`${JELLYFIN_HOST}`) && PathPrefix(`/metrics`)
      traefik.http.routers.jellyfin-metrics.entrypoints: https
      traefik.http.routers.jellyfin-metrics.middlewares: jellyfin-security, local-whitelist
