version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: $GITLAB_HOST
    volumes:
      - ${GITLAB_HOME}/config:/etc/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${GITLAB_HOST}"
        gitlab_rails['gitlab_shell_ssh_port'] = $GITLAB_SSH_PORT
        
        # Nginx params to redirect from traefik
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # Each address is added to the the NGINX config as 'set_real_ip_from <address>;'
        nginx['real_ip_trusted_addresses'] = [ '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16' ]
        # other real_ip config options
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        
        # Disable letsencrypt as traefik handles certificates
        letsencrypt['enable'] = false
        
        # Disable bundled postgres
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_database'] = '${POSTGRES_DB}'
        gitlab_rails['db_username'] = '${POSTGRES_USER}'
        gitlab_rails['db_password'] = '${POSTGRES_PASSWORD}'

        # Disable bundled redis
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379

        # SMTP Settings
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_port'] = '${SMTP_PORT}'
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = '${GITLAB_EMAIL_FROM}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_EMAIL_TO}'

        # Disable incoming mail
        gitlab_rails['incoming_mail_enabled'] = false
        
        # Enable container registry
        registry_external_url 'https://$GITLAB_CONTAINER_REGISTRY_HOST'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_api_url'] = 'https://$GITLAB_CONTAINER_REGISTRY_HOST'
        registry['enable'] = true
        registry_nginx['enable'] = false
        registry['registry_http_addr'] = "0.0.0.0:5000"

        # Authentik SSO
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'saml'
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['saml']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        gitlab_rails['omniauth_providers'] = [
          {
            name: 'saml',
            args: {
              assertion_consumer_service_url: 'https://$GITLAB_HOST/users/auth/saml/callback',
              # Shown when navigating to certificates in authentik
              idp_cert_fingerprint: '$AUTHENTIK_CERT_FINGERPRINT',
              idp_sso_target_url: 'https://$AUTHENTIK_HOST/application/saml/gitlab/sso/binding/redirect/',
              issuer: 'https://$GITLAB_HOST',
              name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
              attribute_statements: {
                email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
                first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'],
                nickname: ['http://schemas.goauthentik.io/2021/02/saml/username']
              }
            },
            label: 'authentik'
          }
        ]
    shm_size: 256m
    depends_on:
      - redis
      - postgres
    ports:
      - $GITLAB_SSH_PORT:22
    labels:
      traefik.enable: true
      # Gitlab routing
      traefik.http.services.gitlab.loadbalancer.server.port: 80
      traefik.http.routers.gitlab.rule: Host(`$GITLAB_HOST`)
      traefik.http.routers.gitlab.entrypoints: https
      traefik.http.routers.gitlab.service: gitlab
      
      # Gitlab container repository routing
      traefik.http.services.gitlab-cr.loadbalancer.server.port: 5000
      traefik.http.routers.gitlab-cr.rule: Host(`$GITLAB_CONTAINER_REGISTRY_HOST`)
      traefik.http.routers.gitlab-cr.entrypoints: https
      traefik.http.routers.gitlab-cr.service: gitlab-cr
      
      homepage.group: Tools
      homepage.name: GitLab
      homepage.icon: gitlab
      homepage.href: https://$GITLAB_HOST
      homepage.description: Development Platform
  
  runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    container_name: gitlab-runner
    environment:
      - name=value
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${GITLAB_HOME}/runner:/etc/gitlab-runner
    depends_on:
      - gitlab
  
  postgres:
    image: postgres:15-alpine
    container_name: gitlab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ${GITLAB_HOME}/postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: gitlab-redis
    restart: unless-stopped
    volumes:
      - ${GITLAB_HOME}/redis:/data
