version: '3.8'
services:
  one-pager:
    image: randomman552/one-pager:latest
    container_name: one-pager
    hostname: $HOST
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.one-pager.loadbalancer.server.port: 80
      traefik.http.routers.one-pager.rule: Host(`${HOST}`) || Host(`www.${HOST}`)
      traefik.http.routers.one-pager.entrypoints: https
      traefik.http.routers.one-pager.tls: true
