version: "3.8"
services:
  tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - $SPEEDTEST_HOME/tracker/config:/config
    labels:
      traefik.enable: true
      traefik.http.services.speedtest-tracker.loadbalancer.server.port: 80
      traefik.http.routers.speedtest-tracker.rule: Host(`$TRACKER_URL`)
      traefik.http.routers.speedtest-tracker.entrypoints: https
      traefik.http.routers.speedtest-tracker.middlewares: local-whitelist
      traefik.http.middlewares.local-whitelist.ipwhitelist.sourcerange: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
      homepage.group: Monitoring
      homepage.name: Speedtest Tracker
      homepage.href: https://$TRACKER_URL
      homepage.icon: speedtest-tracker
      homepage.description: Network speed monitoring

  tester:
    image: openspeedtest/latest
    container_name: speedtest-tester
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.speedtest-tester.loadbalancer.server.port: 3000
      traefik.http.routers.speedtest-tester.rule: Host(`$TESTER_URL`)
      traefik.http.routers.speedtest-tester.entrypoints: https
      traefik.http.routers.speedtest-tester.middlewares: local-whitelist, speedtest-limit
      traefik.http.middlewares.speedtest-limit.buffering.maxRequestBodyBytes: 10000000000
      traefik.http.middlewares.local-whitelist.ipwhitelist.sourcerange: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
      homepage.group: Monitoring
      homepage.name: Speedtest
      homepage.description: Speedtest client
      homepage.href: https://$TESTER_URL
      homepage.icon: openspeedtest