version: '3'
services:
  garrysmod:
    image: randomman552/gmod
    container_name: gmod
    user: ${GMOD_UID:-1600}:${GMOD_PID:-1600}
    tty: true
    restart: unless-stopped
    environment:
      - GAME_MODE=${GAME_MODE:-sandbox}
      - MAP=${MAP:-gm_construct}
      - WORKSHOP_COLLECTION=${WORKSHOP_COLLECTION}
    ports:
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - ${GMOD_HOME:-/pool/games/gmod}/server:/server
      - ${GMOD_HOME:-/pool/games/gmod}/mount:/mount