version: '3'
services:
  server:
    user: $SATISFACTORY_UID:$SATISFACTORY_GID
    container_name: satisfactory-server
    image: wolveix/satisfactory-server:latest
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - $SATISFACTORY_PATH/config:/config
    environment:
      MAXPLAYERS: 64
      ROOTLESS: false
      PGID: $SATISFACTORY_GID
      PUID: $SATISFACTORY_UID
      STEAMBETA: false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G