- name: Install speedtest tracker
  become: true
  community.docker.docker_compose_v2:
    project_name: speedtest
    remove_orphans: true
    definition:
      services:
        # Speed test tracker
        speedtest-tracker:
          image: lscr.io/linuxserver/speedtest-tracker:1.2.3
          restart: unless-stopped
          container_name: speedtest-tracker
          environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY={{ speedtest_tracker_app_key }}
            - DB_CONNECTION=sqlite
          volumes:
            - "{{ speedtest_tracker_home }}/config:/config"
          labels:
            traefik.enable: true
            traefik.http.services.speedtest-tracker.loadbalancer.server.port: 80
            traefik.http.routers.speedtest-tracker.rule: Host(`{{ speedtest_tracker_host }}`)
            traefik.http.routers.speedtest-tracker.entrypoints: https
            traefik.http.routers.speedtest-tracker.middlewares: local-whitelist@docker
