- name: Install traefik
  hosts: git_server
  roles:
    - traefik

- name: Install gitea
  hosts: git_server
  roles:
    - gitea

- name: Install Drone server
  hosts: git_server
  roles:
    - drone
