- name: Common lxc configuration
  hosts: lxcs
  roles:
    - lxc

- name: Common configuration
  hosts: all
  roles:
    - common

- name: Docker
  hosts: docker
  roles:
    - docker

- name: Portainer agent
  hosts: portainer_agent
  roles:
    - portainer-agent

- name: Watchtower
  hosts: watchtower
  roles:
    - watchtower

- name: Traefik
  hosts: traefik
  roles:
    - traefik

- name: Portainer
  hosts: portainer_server
  roles:
    - portainer

- name: PiHole
  hosts: pihole_server
  roles:
    - pihole

- name: Drone Runner
  hosts: ci_runner_server
  roles:
    - drone-runner

- name: Gateway
  hosts: gateway_server
  roles:
    - gateway

- name: Documents Server
  hosts: document_server
  roles:
    - documents

- name: Auth Server
  hosts: auth_server
  roles:
    - authentik
