- name: Common lxc configuration
  hosts: lxcs
  roles:
    - lxc

- name: Common configuration
  hosts: all
  roles:
    - common

- name: Docker
  hosts: docker
  roles:
    - docker

- name: Portainer agent
  hosts: portainer_agent
  roles:
    - docker
    - portainer-agent
