- name: Install uptime kuma
  become: true
  community.docker.docker_compose_v2:
    project_name: uptime-kuma
    remove_orphans: true
    definition:
      services:
        server:
          image: louislam/uptime-kuma:1
          restart: always
          volumes:
            - "{{ uptime_kuma_home }}/data:/app/data"
          labels:
            traefik.enable: true
            traefik.http.services.deluge.loadbalancer.server.port: 3001
            traefik.http.routers.deluge.rule: Host(`{{ uptime_kuma_host }}`)
            traefik.http.routers.deluge.entrypoints: https
