services:
  server:
    image: itzg/minecraft-server:java8
    user: 1600:1600
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: $CF_API_KEY
      CF_SLUG: skyfactory-4
      EULA: true
      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
      ENABLE_ROLLING_LOGS: true
    volumes:
      - /data/minecraft/skyfactory4:/data