version: "3"
services:
  # Watchtower auto updater
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: ${WATCHTOWER_HOSTNAME:-watchtower}
    restart: unless-stopped
    environment:
      TZ: Europe/London

      WATCHTOWER_CLEANUP: true
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-0 0 4 * * *}

      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: https://$GOTIFY_HOST
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: $GOTIFY_TOKEN

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
