services:
  rclone:
    image: rclone/rclone
    container_name: backblaze-rclone
    restart: unless-stopped
    environment:
      RCLONE_B2_ACCOUNT: $ACCOUNT
      RCLONE_B2_KEY: $KEY
    volumes:
      - $RCLONE_HOME/config:/config:rw
      - $DATA_PATH:/data:ro
    entrypoint: crond
    command: -f -l 0 -c /config/crontabs
