services:
  # Scheduling service
  scheduler:
    image: randomman552/rclone-scheduler
    restart: unless-stopped
    environment:
      RCLONE_PROTOCOL: http
      RCLONE_HOST: server
      RCLONE_PORT: $RCLONE_PORT
      BACKUP_SCHEDULE: $BACKUP_SCHEDULE
      BACKUP_REMOTE: $BACKUP_REMOTE
      BACKUP_DEST: $BACKUP_DEST

  # Rclone daemon
  server:
    image: rclone/rclone
    restart: unless-stopped
    ports:
      - 5572:5572
    environment:
      # Create Backblaze B2 config
      RCLONE_CONFIG_B2_ACCOUNT: $B2_ACCOUNT
      RCLONE_CONFIG_B2_KEY: $B2_KEY
      RCLONE_CONFIG_B2_TYPE: b2
      # Global settings
      RCLONE_TRANSFERS: 8
      RCLONE_IGNORE_ERRORS: true
      RCLONE_DELETE_EXCLUDED: true
      RCLONE_FILTER_FROM: $BACKUP_FILTER_FROM
    volumes:
      - $DATA_PATH:/data:ro
    command: rcd --rc-web-gui --rc-addr :${RCLONE_PORT} --rc-web-gui-no-open-browser --rc-no-auth --rc-enable-metrics
    labels:
      # Traefik routing
      traefik.enable: true
      traefik.http.services.rclone.loadbalancer.server.port: $RCLONE_PORT
      traefik.http.routers.rclone.rule: Host(`${RCLONE_HOST}`)
      traefik.http.routers.rclone.entrypoints: https
      traefik.http.routers.rclone.middlewares: local-whitelist, authentik-forwardauth
      
      # Add to homepage
      homepage.group: Management
      homepage.name: Rclone
      homepage.icon: rclone
      homepage.description: Backup Provider
      homepage.href: https://$RCLONE_HOST