services:
  # Scheduling service
  scheduler:
    image: randomman552/rclone-scheduler
    restart: unless-stopped
    environment:
      RCLONE_PROTOCOL: http
      RCLONE_HOST: server
      RCLONE_PORT: $RCLONE_PORT
      BACKUP_SCHEDULE: $BACKUP_SCHEDULE
      BACKUP_REMOTE: $BACKUP_REMOTE
      BACKUP_DEST: $BACKUP_DEST

  # Rclone daemon
  server:
    image: rclone/rclone
    restart: unless-stopped
    environment:
      # Create Backblaze B2 config
      RCLONE_CONFIG_B2_ACCOUNT: $B2_ACCOUNT
      RCLONE_CONFIG_B2_KEY: $B2_KEY
      RCLONE_CONFIG_B2_TYPE: b2
      # Global settings
      RCLONE_TRANSFERS: 16
      RCLONE_IGNORE_ERRORS: true
      RCLONE_IGNORE_SIZE: true
      RCLONE_IGNORE_CHECKSUM: true
      RCLONE_DELETE_EXCLUDED: true
      RCLONE_FILTER_FROM: $BACKUP_FILTER_FROM
    volumes:
      - $DATA_PATH:/data:ro
    command: rcd  --rc-addr :${RCLONE_PORT} --rc-no-auth --rc-enable-metrics
    labels:
      # Traefik routing
      traefik.enable: true
      traefik.http.services.rclone.loadbalancer.server.port: $RCLONE_PORT
      traefik.http.routers.rclone.rule: Host(`${RCLONE_HOST}`) && Path(`/metrics`)
      traefik.http.routers.rclone.entrypoints: https
      traefik.http.routers.rclone.middlewares: local-whitelist