version: '3.8'
services:
  server:
    image: drone/drone
    restart: unless-stopped
    environment:
      DRONE_GITEA_SERVER: https://$GITEA_HOST
      DRONE_GITEA_CLIENT_ID: $GITEA_CLIENT_ID
      DRONE_GITEA_CLIENT_SECRET: $GITEA_CLIENT_SECRET
      DRONE_RPC_SECRET: $DRONE_RPC_SECRET
      DRONE_SERVER_HOST: $DRONE_HOST
      DRONE_SERVER_PROTO: https
    volumes:
      - $DRONE_PATH/data:/var/lib/drone
    labels:
      traefik.enable: true
      traefik.http.services.drone.loadbalancer.server.port: 80
      traefik.http.routers.drone.rule: Host(`$DRONE_HOST`)
      traefik.http.routers.drone.entrypoints: https
      homepage.group: Tools
      homepage.name: Drone
      homepage.icon: drone
      homepage.description: Self-hosted CI Runner
      homepage.href: https://$DRONE_HOST