version: '3.8'
services:
  runner:
    image: drone/drone-runner-docker
    restart: unless-stopped
    container_name: drone-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: https
      DRONE_RPC_HOST: $DRONE_HOST
      DRONE_RPC_SECRET: $DRONE_SECRET
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: docker-runner