version: "3"
services:
  server:
    image: actualbudget/actual-server:latest
    restart: unless-stopped
    volumes:
      - ${ACTUAL_HOME}/data:/data
    labels:
      traefik.enable: true
      traefik.http.services.actual-budget.loadbalancer.server.port: 5006
      traefik.http.routers.actual-budget.rule: Host(`$ACTUAL_HOST`)
      traefik.http.routers.actual-budget.entrypoints: https
      traefik.http.routers.actual-budget.middlewares: local-whitelist