version: '3'
services:
  # Grafana
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    user: "1100"
    networks:
      - monitoring
    volumes:
      - $MONITORING_HOME/grafana:/var/lib/grafana
    labels:
      traefik.enable: true
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.rule: Host(`$GRAFANA_HOST`)
      traefik.http.routers.grafana.entrypoints: https
      homepage.group: Management
      homepage.name: Grafana
      homepage.icon: grafana
      homepage.description: Dashboard monitoring software
      homepage.href: https://$GRAFANA_HOST
      
  # Prometeus data provider
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - $MONITORING_HOME/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $MONITORING_HOME/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
  
  # Node information provider
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  # Influx
  influxdb:
    image: influxdb:2.7
    networks:
      - monitoring
    volumes:
      - $MONITORING_HOME/influx/config:/etc/influxdb
      - $MONITORING_HOME/influx/data:/var/lib/influxdb
    labels:
      traefik.enable: true
      traefik.http.services.influx.loadbalancer.server.port: 8086
      traefik.http.routers.influx.rule: Host(`$INFLUX_HOST`)
      traefik.http.routers.influx.entrypoints: https
      homepage.group: Management
      homepage.name: InfluxDB
      homepage.icon: influx
      homepage.description: Dashboard monitoring software
      homepage.href: https://$INFLUX_HOST

networks:
  monitoring:
    driver: bridge