version: '3.9'
services:
  multiverse:
    image: itzg/minecraft-server:java17-alpine
    container_name: multiverse
    restart: always
    user: 1600:1600
    ports:
      - 25565:25565
    environment:
      - EULA=true
      - TYPE=paper
      - INIT_MEMORY=1G
      - MAX_MEMORY=8G
      - ENABLE_ROLLING_LOGS=true
    volumes:
      - /storage/games/minecraft/multiverse/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minecraft-dynmap.loadbalancer.server.port=8123"
      - "traefik.http.routers.minecraft-dynmap.rule=Host(`dynmap.ggrainger.uk`)"
      - "traefik.http.routers.minecraft-dynmap.entrypoints=https"
      - "traefik.http.routers.minecraft-dynmap.tls=true"