- name: Add non-free-firmware debian
  become: true
  ansible.builtin.deb822_repository:
    enabled: true
    name: debian
    suites:
      - "{{ ansible_facts.distribution_release }}"
    components:
      - non-free-firmware
    uris:
      - http://deb.debian.org/debian

- name: Add non-free debian-updates
  become: true
  ansible.builtin.deb822_repository:
    enabled: true
    name: debian-updates
    suites:
      - "{{ ansible_facts.distribution_release }}-updates"
    components:
      - non-free
    uris:
      - http://deb.debian.org/debian

- name: Add non-free debian-security
  become: true
  ansible.builtin.deb822_repository:
    enabled: true
    name: debian-security
    suites:
      - "{{ ansible_facts.distribution_release }}-security"
    components:
      - non-free
    uris:
      - http://security.debian.org

- name: Install drivers
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: nvidia-driver
    state: present
  notify:
    - Reboot system
